# Generated by Django 2.1.7 on 2019-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_filters', '0003_auto_20180610_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedfilter',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Model'),
        ),
    ]
