# Generated by Django 2.1.7 on 2019-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_filters', '0004_auto_20190221_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedfilter',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
